# DataSource Config
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:dm://localhost:5236
    username: SYSDBA
    password: SYSDBA

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.wrapper: debug